# GitHub Workflow to verify the tests of all answers for 2020.

# Runs all TypeScript/Yarn tests for 2020 projects
name: 2020 Tests

on:
  push:
    branches: [main]
    paths:
      # And only trigger when 2020 directory changes
      - "2020/**"

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Specify all desired node versions
        node-version: [12.x]

    steps:
      # Setup Runner with node
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: actions/cache@v2 (node_modules)
        uses: actions/cache@v2
        # Use this ID to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        id: yarn-cache
        with:
          path: "2020/node_modules/"
          key: ${{ runner.os }}-2020-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-2020-modules-
        # Run all CI actions
      - name: yarn install
        run: yarn install --frozen-lockfile
        working-directory: ./2020
      - name: yarn run test
        run: yarn run test
        working-directory: ./2020
